#    iso_image: 'http://172.16.90.131/iso/CentOS-7-x86_64-Minimal-1810.iso'

---
- hosts: localhost
  vars:
    iLo_IP: '10.2.1.22'
    iLo_username: 'Administrator'
    iLo_password: 'YGEVBUBL'
    iso_image: 'http://172.16.90.131/iso/rhel-server-7.6-x86_64-boot.iso'

  tasks:
    - name: Boot the system with an ISO
      hpilo_boot:
        host: "{{ iLo_IP }}"
        login: "{{ iLo_username }}"
        password: "{{ iLo_password }}"
        media: cdrom
        image: "{{ iso_image }}"
      delegate_to: localhost
    - name: Power off the server
      hpilo_boot:
        host: "{{ iLo_IP }}"
        login: "{{ iLo_username }}"
        password: "{{ iLo_password }}"
        state: boot_once
      delegate_to: localhost

